env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Y+YxuiIsDDP8OqxnB7wQ0o/f8036p/n0hM9zD+tqfXw30ajtQPw45vVFVnBOMrsVZUHeToX+isoAoJQaI8791UqS9Tttl5tb8WjpYDeE1LGsTeUeBh7EmZvVD2xvhGjcrSayBwoQeTf2mxgJKzzfJwrAfq50hkgHIsUijadOmao="

language: java

jdk:
  - oraclejdk7 
  - oraclejdk8
  - openjdk7

after_success:
  bash <(curl -s https://codecov.io/bash)

addons:
  coverity_scan:
    project:
      name: "damianszczepanik/cucumber-reporting"
      description: "Build submitted via Travis CI"
    # Where email notification of build analysis results will be sent
    notification_email: damian.publicemail@gmail.com
    # Commands to prepare for build_command
    build_command_prepend: "mvn clean"
    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    build_command:   "mvn -DskipTests=true compile"
    # Pattern to match selecting branches that will run analysis.
    branch_pattern: master
