env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "BIC0/7IEgiFaOX5VWJMsRit0AEg63oWzYY9BJ9Uu6QK9RLMRykUCtTN16oOrP+30kx4slDc9SEIol4hq31lN8hdSH/FN6XtVMUd/Ao7r8bRH9lmKS3xnODP/P3ki/yf8v3MFR5BCOSwmzyT4Ul5x5Kex8fNAuDd6zikDodb70i0="

language: java

jdk:
  - oraclejdk7 
  - oraclejdk8
  - openjdk7

after_success:
  bash <(curl -s https://codecov.io/bash)

addons:
  coverity_scan:
    project:
      name: "damianszczepanik/cucumber-reporting"
      description: "Build submitted via Travis CI"
    # Where email notification of build analysis results will be sent
    notification_email: damian.publicemail@gmail.com
    # Commands to prepare for build_command
    build_command_prepend: "mvn clean"
    # The command that will be added as an argument to "cov-build" to compile your project for analysis,
    build_command:   "mvn -DskipTests=true compile"
    # Pattern to match selecting branches that will run analysis.
    branch_pattern: master
